### ISSUE TITLE
My prints won't finish

### ISSUE THREAD

**Issue by hebrwhammer587** [alephobjects/Cura#100]
So I start cura, I load in my file and put my designated settings for my lulzbot taz 5 print. I get it heat up and start to get it printing. Hours later I come back from school and I don't see a finished object. My extruder stays still and my printer says printing as well. It didn't finish my object as well and it turned out soo good!

**Comment by jebba** [comment]
Please contact Aleph Objects' Customer Support for this issue with your LulzBot TAZ printer. You can reach them by email at support@lulzbot.com or by calling +1-970-377-1111 weekdays. Thanks.
