### ISSUE TITLE
Machine setup needs TAZ 5 w/ 0.5mm nozzle

### ISSUE THREAD

**Issue by reprapperMC** [alephobjects/Cura#107]
With the coming addition of the TAZ 5 with a 0.5mm nozzle we need to add that selection in the machine  selection menu. We will also need to add the profiles to the quick print settings.

**Comment by reprapperMC** [comment]
Profiles for TAZ w/ 0.5mm nozzle can be found here: https://github.com/alephobjects/print_profiles/tree/master/cura/TAZ_0.5nozzle

Those will likely have one more update before the final release.

**Comment by nickthetait** [comment]
Fixed and merged https://github.com/alephobjects/Cura/commit/8b5e804e7ed2c50c19441b4037d4cd90b0015c87
