### ISSUE TITLE
Print all at once should be default state

### ISSUE THREAD

**Issue by reprapperMC** [alephobjects/Cura#110]
In a build from LulzBot-devel branch with commit 608ef48b15b8159fd1e760137935cc6b7112085d, Print one at a time is set as default. This should be Print All at Once as default. All at once is more common and I believe having one at a time as default may cause some confusion for users and unnecessary support calls.

**Comment by kakaroto** [comment]
You're right, print one at a time was enabled by default, we'd only notice it once the gantry settings are set. I've changed the default to False now.
