### ISSUE TITLE
Clear Platform Doesn't Always Work

### ISSUE THREAD

**Issue by gwlinn** [alephobjects/Cura#112]

**Comment by gwlinn** [comment]
Several times, I used "Clear Platform" in order to build a different object.  The platform appeared to close and I loaded the new object.  However, when I began printing, I saw that Cura was printing the previous object.  So, I now routinely close and reopen Cura to make sure the new object will be printed.

**Comment by kakaroto** [comment]
If you had the Print controller open, you would need to close it and reopen it. Once the print controller is open, it will print whatever was on the bed at that time, this allows you to keep manipulating your print bed without affecting your current print.

**Comment by nickthetait** [comment]
@gwlinn If you run into this problem all you have to do is close the print window and then click "control" again. See #114 for why this is being closed.
