### ISSUE TITLE
Cura folder conflicts with cura on case insensitive file systems

### ISSUE THREAD

**Issue by Jnesselr** [alephobjects/Cura#122]
If you clone Cura and then switch to the devel branch on a case insensitive file system, git will get confused because the folder Cura and the file cura look exactly the same to it. Because of this, when the file is created, the folder itself is removed and everything under it. When you tell git to restore the folder using git checkout -- Cura then the cura file disappears. And then, of course, if you run git checkout -- cura then the folder disappears.

**Comment by nickthetait** [comment]
I'm on it...
