### ISSUE TITLE
Changing flow % setting in Cura does not affect flow

### ISSUE THREAD

**Issue by familiarCatch** [alephobjects/Cura#125]
14.09-1.18.7

Adjusting the ~~flow rate~~ flow % in Cura has no affect on the flow.

It definitely could be me, let me know what I can do to help.

**Comment by nickthetait** [comment]
Are you adjusting the flow rate via the LCD panel on a Taz?

**Comment by familiarCatch** [comment]
Adjusting the flow on the LCD works correctly, adjusting flow through Cura does not.

**Comment by kakaroto** [comment]
Cura doesn't have a "flow rate" option similar to the one on the LCD. The LCD flow rate option basically slows down or speeds up the printing, but the "Flow (%) " option in Cura under the Filament section is used to compensate for extrusion settings and if you save the gcode from 100% flow to a 95% flow, and diff the two files, you'll see that the flow option is taken into consideration.
The flow % option in Cura is basically the same as the "Extrusion multiplier" in Slic3r, and it's there to compensate for over or under extrusion by fine tuning how much filament is extruded without messing with the filament diameter or the E-steps in the firmware.

**Comment by nickthetait** [comment]
So this is a labeling issue. Right now it is displayed as "Flow %". What would better match the actual usage?

**Comment by kakaroto** [comment]
I don't think it's a labeling issue, it's listed under Filament, just below diameter, it indicates the filament flow %.. even on slic3r, the extrusion multiplier is as a percentage. Either way, the tooltip explains it pretty well. I think the real naming issue is with the "flow rate" from LCD which confused me a lot at first because it's actually just a "speed modifier" and I couldn't understand why it was called "flow rate".

**Comment by familiarCatch** [comment]
Under Filament in Cura, the Flow % option does nothing for me. If it is set to 0, or 100, it prints the same.

**Comment by nickthetait** [comment]
I can verify that changing that number does have an affect.
* 0% gives no material flow except for a little dribbling
* 100% is the normal good looking print
* 200% is ugly, deformed, and inconsistent 

What printer are you using? Could you describe your exact steps to reproduce the problem? Please include stl and profile that you are using.

**Comment by nickthetait** [comment]
Without any more details I can't provide any more help.
