### ISSUE TITLE
UI buttons are not disabled during printing

### ISSUE THREAD

**Issue by nickthetait** [alephobjects/Cura#126]
Steps to reproduce:
Start a print
Click any one (or more) of [X/Y/Z/Extrude] [+/-/home]

Expected:
Buttons are grayed out while printing, so any clicks of these buttons are ignored. (Temperature changes should still be allowed mid print.)

Actual:
Current command finishes, button click command is added, then printing continues. X and Y moves gets re-positioned (unless you run into an endstop). Z movements do not get reset until a layer finishes.

Personally I think that it is kinda stupid that anyone would try this. But the consequences of an accidental click could ruin a print and/or damage your printer so this is worth fixing. Plus the behavior is downright confusing and silly!

**Comment by kakaroto** [comment]
Done in commit cef8cc8c685e699b22410fae60970eb537d02f6b (forgot to reference this issue in the commit message).
