### ISSUE TITLE
Save gcode to SD does not prompt for save location

### ISSUE THREAD

**Issue by orias** [alephobjects/Cura#23]
When saving the gcode through the button after a print, it does not prompt to save in a custom location.

**Comment by kakaroto** [comment]
If more than one drive is mounted, it will give you the choice for which SD card to save the file to. I just tested it by mounting two drives to /media/ and it gives me the choice.
I've now pushed a fix though to have that list always show up (even if you have only one removable drive) and have a "Custom file destination" option in the list as well.
