### ISSUE TITLE
Debian control files need to auto fill with version and commit hash

### ISSUE THREAD

**Issue by reprapperMC** [alephobjects/Cura#31]

**Comment by kakaroto** [comment]
It looks like it was started upstream here : https://github.com/daid/Cura/commit/4fec8120f77acfc93d118a3736ee7a566d3631de
It could be improved by using the same script and adding the commit hash if the version contain 'RC' for example. I'd suggest resolving this issue after we pull in those changes (they are in the 15.01 branch)

**Comment by reprapperMC** [comment]
This is done per commit e9c2d2d574e4f2fde4a3faf0eafa8b0062834bea
