### ISSUE TITLE
Cura Plugins not getting shut off when switching profiles

### ISSUE THREAD

**Issue by brentmac** [alephobjects/Cura#59]
Cura seems to be leaving plugins active even when switching profiles and materials. This could mess some things up, I had PLA profiles bumping the bed temp from 65 to 85 and causing some really strange failures.

Try opening the full setting version of cura and turning on the "tweak at Z" plugin and have it change the bed temperature.

Now if you switch to quick settings or even close and re-open cura in the quick settings, this plugin will still be active. If you open up the gcode in a text editor you can tell that the plugin is active when it shows this
 ;TweakAtZ V3.2: executed at 2.00 mm 
 a couple of times in the gcode, and usually somewhere in the startup gcode

I think we might need it th clear out any active plugins and then reapply them for the simple settings

**Comment by kakaroto** [comment]
I'm not sure if this is the solution you were looking for, but I've fixed it. There was indeed a bug that made it ignore the fact that quick print settings should not have any plugins enabled (see https://github.com/alephobjects/Cura/commit/4a9bb212ddf975e8c2848e475e39c43e1862dc7f).

If this is what you wanted, then please close the issue.

**Comment by reprapperMC** [comment]
If the plugins could be set in simpleMode.py that would be great, but I do not think the plugin settings set in the hard coded simple mode profiles is connected to push those settings to the plugin.

**Comment by kakaroto** [comment]
Merged into master.
