### ISSUE TITLE
Z offset feature

### ISSUE THREAD

**Issue by reprapperMC** [alephobjects/Cura#6]
There was a request for a Z offset setting. This would probably be best made as a machine setting.

**Comment by kakaroto** [comment]
Agreed.
I think I should also move it above the "Extruder count" option. the help text does need to be reviewed. I copied it pretty much from the slicer setting text.
Weird thing is that for me, I don't see any tooltips in the machine settings.(or in print settings) in Linux. Is it just me or is this a linux bug ?

**Comment by Jnesselr** [comment]
I modified the machine settings tooltips. Originally, they were undecorated
windows that would pop up in the correct position. This caused some
problems when the build that we couldn't figure out, so I moved them to
actual tooltips. The result of this is that the operating system determines
how long before it shows the tooltip. I can try to revert it back to the
old way and fix the problems with it if we want.

The original problem was that hovering over a field in the settings dialog
would cause the entire window to disappear behind the main one on Mac.

**Comment by kakaroto** [comment]
I'll check, if it works on Mac, then great, if it doesn't work on linux/windows, then we can leave your modification for mac only.

**Comment by kakaroto** [comment]
I checked the latest version then tested both the commit where you made the change and the one before and tooltips are not working since your change in Windows as well.
I've filed issue #74 for it.

**Comment by kakaroto** [comment]
Merged into master. Don't forget to pull in the changes from CuraEngine when building, I've merged the required changes into CuraEngine's master as well.
