### ISSUE TITLE
Model doesn't appear when loading and layer view is selected 

### ISSUE THREAD

**Issue by kakaroto** [alephobjects/Cura#96]
If a new model is loaded into Cura where none was there before, and the layers view was already selected by default, then nothing will appear on the plate.
Steps to reproduce : 
* Load a model
* Select layers view
* delete all objects
* Load a new model

Version tested : 15.02.1 (https://github.com/alephobjects/Cura/commit/427d2e35a24751be7f87e10b09626217888ef744)

**Comment by Jnesselr** [comment]
Yep. It seems that it doesn't switch to the model view again.

**Comment by kakaroto** [comment]
Fixed now! Closing.
